### PR TITLE
Quarantine regex is too restrictive

### PR DESCRIPTION
**Pull request by aaronbarker**
The quarantine regex only allowed for OS 5_1, but not 5 or 5_1_1 (the current version). My regex-fu may not be perfect, but I believe the modification should allow for all 3 of the above.

### CODE REVIEW

**Comment by scottjehl** [comment]
Thanks, but this should have landed already in master (as of yesterday). 

Is it not working properly currently for you?

**Comment by aaronbarker** [comment]
It is not working for me. I'm on 5_1_1 but the regex only checks for [1-5]_\d (no second _1) so fails.

**Comment by Scotchester** [comment]
Looks like it's landed in the .js but has not been updated in the minified code in the readme.

**Comment by scottjehl** [comment]
Looks fine to me? https://github.com/scottjehl/iOS-Orientationchange-Fix#readme

**Comment by Scotchester** [comment]
Weird... says you made that change 34 minutes ago, but I'm pretty sure I saw it more recently without that change... A caching issue, perhaps. I definitely copied it less than an hour ago with the old regex.

**Comment by aaronbarker** [comment]
Cool thanks for the fix.

If I might ask, for my own education, what makes your regex better than mine?
Yours: [1-5]_[0-9_]*
Mine: [1-5][_\d]*

This was my first patch submission, so just trying to be educated if it is easier to make a change as the author than accept a pull request, or if the regex is better in some way.

Not trying to be flippant or challenging, just trying to learn :)

**Comment by scottjehl** [comment]
Ah, actually yours looks better I think. I was merely pointing out that when this pull came in, the fix was already in master. If you want to resend this as a commit on top of master, I'd be happy to pull it in.

Thanks!

**Pull request closed without merging**
